const ITEMS = [
  // === LEATHER SET (common) ===
  {
    id: "leather_cap",
    name: "Leather Cap",
    slot: "head",
    set: "leather",
    rarity: "common",
    stats: { defense: 1, maxHp: 5 },
    minFloor: 1,
    cost: 30,
  },
  {
    id: "leather_vest",
    name: "Leather Vest",
    slot: "body",
    set: "leather",
    rarity: "common",
    stats: { defense: 2, maxHp: 10 },
    minFloor: 1,
    cost: 50,
  },
  {
    id: "leather_boots",
    name: "Leather Boots",
    slot: "feet",
    set: "leather",
    rarity: "common",
    stats: { defense: 1, speed: 10 },
    minFloor: 1,
    cost: 35,
  },
  // === IRON SET (uncommon) ===
  {
    id: "iron_helm",
    name: "Iron Helm",
    slot: "head",
    set: "iron",
    rarity: "uncommon",
    stats: { defense: 3, maxHp: 15 },
    minFloor: 3,
    cost: 80,
  },
  {
    id: "iron_plate",
    name: "Iron Plate",
    slot: "body",
    set: "iron",
    rarity: "uncommon",
    stats: { defense: 5, maxHp: 20 },
    minFloor: 3,
    cost: 120,
  },
  {
    id: "iron_greaves",
    name: "Iron Greaves",
    slot: "feet",
    set: "iron",
    rarity: "uncommon",
    stats: { defense: 2, speed: 5 },
    minFloor: 3,
    cost: 90,
  },
  // === SHADOW SET (rare) ===
  {
    id: "shadow_hood",
    name: "Shadow Hood",
    slot: "head",
    set: "shadow",
    rarity: "rare",
    stats: { defense: 2, speed: 20, crit: 5 },
    minFloor: 6,
    cost: 180,
  },
  {
    id: "shadow_cloak",
    name: "Shadow Cloak",
    slot: "body",
    set: "shadow",
    rarity: "rare",
    stats: { defense: 4, speed: 15, crit: 5 },
    minFloor: 6,
    cost: 220,
  },
  {
    id: "shadow_steps",
    name: "Shadow Steps",
    slot: "feet",
    set: "shadow",
    rarity: "rare",
    stats: { defense: 2, speed: 30 },
    minFloor: 6,
    cost: 190,
  },
  // === FIRE SET (epic) ===
  {
    id: "fire_crown",
    name: "Fire Crown",
    slot: "head",
    set: "fire",
    rarity: "epic",
    stats: { defense: 4, attack: 3, maxHp: 20 },
    minFloor: 10,
    cost: 350,
  },
  {
    id: "fire_armor",
    name: "Fire Armor",
    slot: "body",
    set: "fire",
    rarity: "epic",
    stats: { defense: 7, attack: 2, maxHp: 30 },
    minFloor: 10,
    cost: 400,
  },
  {
    id: "fire_treads",
    name: "Fire Treads",
    slot: "feet",
    set: "fire",
    rarity: "epic",
    stats: { defense: 3, speed: 15, attack: 2 },
    minFloor: 10,
    cost: 360,
  },
  // === VOID SET (legendary) ===
  {
    id: "void_mask",
    name: "Void Mask",
    slot: "head",
    set: "void",
    rarity: "legendary",
    stats: { defense: 6, attack: 5, maxHp: 30, crit: 5 },
    minFloor: 16,
    cost: 600,
  },
  {
    id: "void_robe",
    name: "Void Robe",
    slot: "body",
    set: "void",
    rarity: "legendary",
    stats: { defense: 9, attack: 4, maxHp: 40 },
    minFloor: 16,
    cost: 700,
  },
  {
    id: "void_walkers",
    name: "Void Walkers",
    slot: "feet",
    set: "void",
    rarity: "legendary",
    stats: { defense: 4, speed: 35, crit: 5 },
    minFloor: 16,
    cost: 620,
  },
  // === WEAPONS - each has unique knockback, speed, range ===
  // Daggers: fast, low knockback, low range
  {
    id: "rusty_dagger",
    name: "Rusty Dagger",
    slot: "weapon",
    set: "leather",
    rarity: "common",
    stats: { attack: 2 },
    minFloor: 1,
    cost: 25,
    weapon: {
      knockback: 80,
      atkSpeed: 0.18,
      range: 22,
      size: { w: 24, h: 8 },
    },
  },
  {
    id: "shadow_dagger",
    name: "Shadow Dagger",
    slot: "weapon",
    set: "shadow",
    rarity: "rare",
    stats: { attack: 6, crit: 15 },
    minFloor: 6,
    cost: 190,
    weapon: {
      knockback: 90,
      atkSpeed: 0.15,
      range: 24,
      size: { w: 26, h: 8 },
    },
  },
  {
    id: "void_fang",
    name: "Void Fang",
    slot: "weapon",
    set: "void",
    rarity: "legendary",
    stats: { attack: 14, crit: 12 },
    minFloor: 16,
    cost: 650,
    weapon: {
      knockback: 100,
      atkSpeed: 0.13,
      range: 26,
      size: { w: 28, h: 8 },
    },
  },
  // Swords: balanced
  {
    id: "wooden_sword",
    name: "Wooden Sword",
    slot: "weapon",
    set: "leather",
    rarity: "common",
    stats: { attack: 3 },
    minFloor: 1,
    cost: 40,
    weapon: {
      knockback: 150,
      atkSpeed: 0.3,
      range: 30,
      size: { w: 32, h: 10 },
    },
  },
  {
    id: "steel_sword",
    name: "Steel Sword",
    slot: "weapon",
    set: "iron",
    rarity: "uncommon",
    stats: { attack: 6 },
    minFloor: 3,
    cost: 100,
    weapon: {
      knockback: 180,
      atkSpeed: 0.28,
      range: 32,
      size: { w: 34, h: 10 },
    },
  },
  {
    id: "flame_sword",
    name: "Flame Sword",
    slot: "weapon",
    set: "fire",
    rarity: "epic",
    stats: { attack: 12 },
    minFloor: 10,
    cost: 380,
    weapon: {
      knockback: 200,
      atkSpeed: 0.28,
      range: 34,
      size: { w: 36, h: 12 },
    },
  },
  {
    id: "void_reaper",
    name: "Void Reaper",
    slot: "weapon",
    set: "void",
    rarity: "legendary",
    stats: { attack: 18, crit: 8 },
    minFloor: 16,
    cost: 680,
    weapon: {
      knockback: 220,
      atkSpeed: 0.25,
      range: 36,
      size: { w: 38, h: 12 },
    },
  },
  // Hammers: slow, huge knockback, short range
  {
    id: "wooden_mallet",
    name: "Wooden Mallet",
    slot: "weapon",
    set: "leather",
    rarity: "common",
    stats: { attack: 5 },
    minFloor: 1,
    cost: 45,
    weapon: {
      knockback: 300,
      atkSpeed: 0.5,
      range: 24,
      size: { w: 28, h: 16 },
    },
  },
  {
    id: "iron_hammer",
    name: "Iron Hammer",
    slot: "weapon",
    set: "iron",
    rarity: "uncommon",
    stats: { attack: 9 },
    minFloor: 3,
    cost: 110,
    weapon: {
      knockback: 350,
      atkSpeed: 0.48,
      range: 26,
      size: { w: 30, h: 16 },
    },
  },
  {
    id: "fire_maul",
    name: "Fire Maul",
    slot: "weapon",
    set: "fire",
    rarity: "epic",
    stats: { attack: 16 },
    minFloor: 10,
    cost: 400,
    weapon: {
      knockback: 400,
      atkSpeed: 0.45,
      range: 28,
      size: { w: 32, h: 18 },
    },
  },
  // Spears: medium speed, long range, low knockback
  {
    id: "wooden_spear",
    name: "Wooden Spear",
    slot: "weapon",
    set: "leather",
    rarity: "common",
    stats: { attack: 3 },
    minFloor: 1,
    cost: 35,
    weapon: {
      knockback: 100,
      atkSpeed: 0.32,
      range: 42,
      size: { w: 44, h: 6 },
    },
  },
  {
    id: "iron_lance",
    name: "Iron Lance",
    slot: "weapon",
    set: "iron",
    rarity: "uncommon",
    stats: { attack: 5 },
    minFloor: 3,
    cost: 95,
    weapon: {
      knockback: 120,
      atkSpeed: 0.3,
      range: 46,
      size: { w: 48, h: 6 },
    },
  },
  {
    id: "shadow_pike",
    name: "Shadow Pike",
    slot: "weapon",
    set: "shadow",
    rarity: "rare",
    stats: { attack: 7, crit: 8 },
    minFloor: 6,
    cost: 200,
    weapon: {
      knockback: 130,
      atkSpeed: 0.28,
      range: 48,
      size: { w: 50, h: 6 },
    },
  },
  // Axes: medium speed, high damage, good knockback
  {
    id: "hand_axe",
    name: "Hand Axe",
    slot: "weapon",
    set: "iron",
    rarity: "uncommon",
    stats: { attack: 8 },
    minFloor: 4,
    cost: 105,
    weapon: {
      knockback: 250,
      atkSpeed: 0.38,
      range: 28,
      size: { w: 30, h: 14 },
    },
  },
  {
    id: "fire_axe",
    name: "Fire Axe",
    slot: "weapon",
    set: "fire",
    rarity: "epic",
    stats: { attack: 14, crit: 5 },
    minFloor: 10,
    cost: 390,
    weapon: {
      knockback: 280,
      atkSpeed: 0.35,
      range: 30,
      size: { w: 32, h: 14 },
    },
  },
  // Whips: fast, medium range, low knockback, hits multiple
  {
    id: "leather_whip",
    name: "Leather Whip",
    slot: "weapon",
    set: "leather",
    rarity: "common",
    stats: { attack: 2 },
    minFloor: 2,
    cost: 38,
    weapon: {
      knockback: 60,
      atkSpeed: 0.22,
      range: 38,
      size: { w: 40, h: 6 },
    },
  },
  {
    id: "shadow_lash",
    name: "Shadow Lash",
    slot: "weapon",
    set: "shadow",
    rarity: "rare",
    stats: { attack: 5, crit: 10, speed: 10 },
    minFloor: 7,
    cost: 210,
    weapon: {
      knockback: 70,
      atkSpeed: 0.2,
      range: 42,
      size: { w: 44, h: 6 },
    },
  },
];
const CONSUMABLES = [
  {
    id: "hp_potion",
    name: "Health Potion",
    desc: "Restore 50 HP",
    cost: 20,
    effect: "heal",
    value: 50,
    icon: 0xff4444,
  },
  {
    id: "big_hp_potion",
    name: "Greater Potion",
    desc: "Restore 120 HP",
    cost: 50,
    effect: "heal",
    value: 120,
    icon: 0xff2222,
    minFloor: 5,
  },
  {
    id: "bomb",
    name: "Bomb",
    desc: "40 AoE damage",
    cost: 25,
    effect: "bomb",
    value: 40,
    icon: 0xffaa00,
  },
  {
    id: "big_bomb",
    name: "Mega Bomb",
    desc: "100 AoE damage",
    cost: 60,
    effect: "bomb",
    value: 100,
    icon: 0xff6600,
    minFloor: 8,
  },
  {
    id: "shield_scroll",
    name: "Shield Scroll",
    desc: "Block 3 hits",
    cost: 40,
    effect: "shield",
    value: 3,
    icon: 0x44aaff,
    minFloor: 3,
  },
  {
    id: "atk_elixir",
    name: "Attack Elixir",
    desc: "+5 ATK this floor",
    cost: 35,
    effect: "tempAtk",
    value: 5,
    icon: 0xff8844,
    minFloor: 4,
  },
  {
    id: "spd_elixir",
    name: "Speed Elixir",
    desc: "+30 SPD this floor",
    cost: 30,
    effect: "tempSpd",
    value: 30,
    icon: 0x44ffaa,
    minFloor: 4,
  },
];
const SET_BONUSES = {
  leather: {
    2: { defense: 1, label: "Leather 2pc: +1 DEF" },
    3: { maxHp: 15, label: "Leather 3pc: +15 HP" },
    4: { regen: 1, label: "Leather 4pc: Regen" },
  },
  iron: {
    2: { defense: 3, label: "Iron 2pc: +3 DEF" },
    3: { maxHp: 25, label: "Iron 3pc: +25 HP" },
    4: { thorns: 2, label: "Iron 4pc: Thorns" },
  },
  shadow: {
    2: { speed: 20, label: "Shadow 2pc: +20 SPD" },
    3: { crit: 15, label: "Shadow 3pc: +15% Crit" },
    4: { doubleJump: true, label: "Shadow 4pc: Double Jump" },
  },
  fire: {
    2: { attack: 5, label: "Fire 2pc: +5 ATK" },
    3: { maxHp: 40, label: "Fire 3pc: +40 HP" },
    4: { fireAura: 3, label: "Fire 4pc: Fire Aura" },
  },
  void: {
    2: { attack: 8, label: "Void 2pc: +8 ATK" },
    3: { crit: 20, label: "Void 3pc: +20% Crit" },
    4: { lifesteal: 15, label: "Void 4pc: 15% Lifesteal" },
  },
};
const TALENTS = [
  {
    id: "vitality",
    name: "Vitality",
    desc: "+15 HP",
    maxRank: 5,
    effect: { maxHp: 15 },
  },
  {
    id: "strength",
    name: "Strength",
    desc: "+2 ATK",
    maxRank: 5,
    effect: { attack: 2 },
  },
  {
    id: "armor",
    name: "Toughness",
    desc: "+2 DEF",
    maxRank: 5,
    effect: { defense: 2 },
  },
  {
    id: "agility",
    name: "Agility",
    desc: "+10 SPD",
    maxRank: 3,
    effect: { speed: 10 },
  },
  {
    id: "critical",
    name: "Precision",
    desc: "+5% Crit",
    maxRank: 3,
    effect: { crit: 5 },
  },
  {
    id: "vampirism",
    name: "Vampirism",
    desc: "+5% LS",
    maxRank: 3,
    effect: { lifesteal: 5 },
  },
  {
    id: "dash_master",
    name: "Dash Master",
    desc: "-0.15s CD",
    maxRank: 3,
    effect: { dashCdReduce: 0.15 },
  },
  {
    id: "treasure",
    name: "Treasure",
    desc: "+15% Gold",
    maxRank: 3,
    effect: { goldBonus: 15 },
  },
];
const ENEMY_DEFS = {
  slime: {
    hp: 15,
    attack: 3,
    defense: 1,
    speed: 40,
    xp: 10,
    gold: 5,
    color: 0x44cc44,
    w: 24,
    h: 20,
    aggroRange: 150,
  },
  bat: {
    hp: 10,
    attack: 4,
    defense: 0,
    speed: 70,
    xp: 15,
    gold: 8,
    color: 0x8844aa,
    w: 22,
    h: 18,
    aggroRange: 200,
  },
  skeleton: {
    hp: 30,
    attack: 6,
    defense: 3,
    speed: 50,
    xp: 25,
    gold: 15,
    color: 0xcccccc,
    w: 22,
    h: 28,
    aggroRange: 220,
  },
  demon: {
    hp: 60,
    attack: 10,
    defense: 5,
    speed: 60,
    xp: 50,
    gold: 30,
    color: 0xcc2222,
    w: 28,
    h: 30,
    aggroRange: 250,
  },
  ghost: {
    hp: 25,
    attack: 8,
    defense: 0,
    speed: 80,
    xp: 30,
    gold: 20,
    color: 0xaaccff,
    w: 22,
    h: 24,
    aggroRange: 200,
  },
  golem: {
    hp: 100,
    attack: 12,
    defense: 8,
    speed: 25,
    xp: 60,
    gold: 35,
    color: 0x887744,
    w: 30,
    h: 32,
    aggroRange: 180,
  },
};
const BOSS_DEFS = {
  slime_king: {
    hp: 200,
    attack: 8,
    defense: 4,
    speed: 35,
    xp: 150,
    gold: 100,
    color: 0x22aa22,
    w: 48,
    h: 40,
    name: "Slime King",
  },
  bone_lord: {
    hp: 350,
    attack: 14,
    defense: 6,
    speed: 45,
    xp: 250,
    gold: 180,
    color: 0xddddcc,
    w: 44,
    h: 48,
    name: "Bone Lord",
  },
  inferno_wyrm: {
    hp: 500,
    attack: 20,
    defense: 8,
    speed: 55,
    xp: 400,
    gold: 280,
    color: 0xff4422,
    w: 52,
    h: 44,
    name: "Inferno Wyrm",
  },
  frost_titan: {
    hp: 650,
    attack: 24,
    defense: 12,
    speed: 40,
    xp: 500,
    gold: 350,
    color: 0x88ccff,
    w: 56,
    h: 52,
    name: "Frost Titan",
  },
  void_emperor: {
    hp: 900,
    attack: 30,
    defense: 15,
    speed: 60,
    xp: 700,
    gold: 500,
    color: 0x6633aa,
    w: 56,
    h: 56,
    name: "Void Emperor",
  },
};
function getBoss(f) {
  if (f === 5) return "slime_king";
  if (f === 10) return "bone_lord";
  if (f === 15) return "inferno_wyrm";
  if (f === 20) return "frost_titan";
  if (f % 5 === 0 && f > 20) return "void_emperor";
  return null;
}
